---
title: "Agronomic_data_plots"
author: "sss322"
date: "2025-01-30"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 0. **Importing the dataset** 
```{r}
library(ASRtriala)
library(dplyr)
library(ggplot2)
library(tidyr)
load("data/wmb_multi_alldata.Rdata")
```



## 1. **Histograms for each agronomic trait over the years** 
```{r, echo=FALSE}
multi$Env <- as.factor(multi$Env)
# Define indices and environment levels
traits<- c("HD_JD", "Ht", "winter_survival", "yield_kgha") 
#indices <- c("red_edge", "green", "blue", "red", "nir")
env_levels <- levels(multi$Env)

# Loop over each environment and index

  for (index in traits) {
    # Subset data for the current environment
    data_subset <- multi
    
    # Create histogram
    histogram <- ggplot(data_subset, aes(.data[[index]])) +
      geom_histogram(fill = "skyblue", color = "black") +
      facet_wrap(~ Env) +
      labs(x = index, y = "Count", title = paste("Histogram of", index)) +
      theme_minimal()
    
    # Print the histogram
    print(histogram)
  }
```


 
## 2. **Boxplots of traits over the years** 
```{r, echo=FALSE}
multi_long <- multi %>%
  pivot_longer(
    cols = all_of(traits), # Columns to pivot
    names_to = "Trait",     # New column for index names
    values_to = "Value"     # New column for index values
  )

for (index in traits) {
  multi_long1<- multi_long %>% filter(multi_long$Trait == index) 
  p <- ggplot(multi_long1, aes(x = Env, y = Value)) +
    geom_boxplot() +
    labs(y = "Value", title = index) +
    theme(legend.position = "none")

  print(p)
}
```





## 3. **Spatial correlation setup and analysis** 
```{r, warning=FALSE}
# Get unique levels of Env
env_levels <- unique(multi$Env)
multi$Row<- as.numeric(multi$Row)
multi$Column<- as.numeric(multi$Column)
# Initialize an empty list to store results
results_list <- list()
for (env in env_levels) {
  for (index in traits) {
  # Filter data for the current environment
  multi_env <- multi %>% filter(Env == env) %>% filter(timepoint == "1")
  multi_env$GID<- as.factor(multi_env$GID)
  multi_env$Row<- as.factor(multi_env$Row)
  multi_env$Column<- as.factor(multi_env$Column)
  # Perform the analysis
  result <- ASRtriala::audit.single(data = multi_env, gen = "GID", row = "Row", col = "Column", resp = index)
  # Store the result in the list with a descriptive name
  results_list[[paste0("Env_", env,"_", index)]] <- result
  }
}

# Printing the plots
for (name in names(results_list)) {
  # Access and display the trial plot for the current result
  print(results_list[[name]]$trial.plot)
  print(results_list[[name]]$trial.plot$data$Env[1])
  #print(results_list[[name]]$trial.plot$data)
  # Optionally, print a message to the console for tracking
  cat(name, "\n")
}

# Save the results to a file
save(results_list, file= "agronomic_correlation_specs_VI_s.Rdata")
```


