---
title: "Untitled"
author: "sss322"
date: "2025-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## **0. Import packages and data**
```{r, message=FALSE}
pkgs <- c("MASS","dplyr","tidyr","asreml","ASRtriala","ASRgenomics",
          "ggplot2","openxlsx","workflowr","readxl", "forcats", "scales")
suppressPackageStartupMessages(invisible(lapply(pkgs, require, character.only = TRUE)))
```

```{r}
paths <- c("C:/Users/Siim Sepp/NY_WMB/data",
           "~/Documents/GitHub/NY_WMB/data",
           "data")

files <- c("data_ag.Rdata","data_mq.Rdata","data_sp.Rdata","VImat.Rdata")

load_first <- function(fname, dirs = paths) {
  for (d in dirs) {
    p <- file.path(path.expand(d), fname)
    if (file.exists(p)) { load(p, envir = .GlobalEnv); return(invisible(p)) }
  }
  stop("File not found in any known location: ", fname)
}
invisible(lapply(files, load_first))
```




### **Calculating heritability for heading traits**
```{r, message=FALSE}
#2021
data<- data_ag
#Select traits and environments
traits <- colnames(data_ag)[8]
e  <- levels(data_ag$Env)[2]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ GID ,#+ ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V2/r))
H$type<- rownames(H)
rownames(H)<- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) ,#+ ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V2/r))
h$type<- rownames(h)
rownames(h) <- NULL

HD21<- rbind(h, H)
HD21$Env<- "KET21"
HD21$Trait<- "HD"

#2022
#Select traits and environments
e   <- levels(data_ag$Env)[5]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ GID + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V5/r))
H$type<- rownames(H)
rownames(H)<- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V5/r))
h$type<- rownames(h)
rownames(h)<- NULL

HD22<- rbind(h, H)
HD22$Env<- "SNY22"
HD22$Trait<- "HD"


#2023
#Select traits and environments
e   <- levels(data_ag$Env)[3]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ GID + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V5/r))
H$type<- rownames(H)
rownames(H) <- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V5/r))
h$type<- rownames(h)
rownames(h)<- NULL

HD23<- rbind(h, H)
HD23$Env<- "MCG23"
HD23$Trait<- "HD"


#2024
#Select traits and environments
e   <- levels(data_ag$Env)[1]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ GID + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V5/r))
H$type<- rownames(H)
rownames(H)<- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V5/r))
h$type<- rownames(h)
rownames(h) <- NULL

HD24<- rbind(h, H)
HD24$Env<- "HELF24"
HD24$Trait<- "HD"



#2025
#Select traits and environments
e   <- levels(data_ag$Env)[4]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ Row + Column")),
  random   = ~ GID ,#+ ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V2/r))
H$type<- rownames(H)
rownames(H) <- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) ,#+ ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V2/r))
h$type<- rownames(h)
rownames(h) <- NULL

HD25<- rbind(h, H)
HD25$Env<- "MCG25"
HD25$Trait<- "HD"




HD<- rbind(HD21, HD22, HD23, HD24, HD25)
HD
```




### **Calculating heritability for yield*
```{r, message=FALSE}
#2021
#Select traits and environments
traits <- colnames(data_ag)[7]
e  <- levels(data_ag$Env)[2]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ Row + Column")),
  random   = ~ GID ,#+ ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V2/r))
H$type<- rownames(H)
rownames(H)<- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V2/r))
h$type<- rownames(h)
rownames(h) <- NULL

HD21<- rbind(h, H)
HD21$Env<- "KET21"


#2022
#Select traits and environments
e   <- levels(data_ag$Env)[5]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ GID + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V5/r))
H$type<- rownames(H)
rownames(H)<- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V5/r))
h$type<- rownames(h)
rownames(h)<- NULL

HD22<- rbind(h, H)
HD22$Env<- "SNY22"



#2023
#Select traits and environments
e   <- levels(data_ag$Env)[3]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ Row + Column")),
  random   = ~ GID ,#+ ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V2/r))
H$type<- rownames(H)
rownames(H) <- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ Row + Column")),
  random   = ~ vm(GID, Ginv.sparse) ,#+ ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V2/r))
h$type<- rownames(h)
rownames(h)<- NULL

HD23<- rbind(h, H)
HD23$Env<- "MCG23"



#2024
#Select traits and environments
e   <- levels(data_ag$Env)[1]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ GID + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V5/r))
H$type<- rownames(H)
rownames(H)<- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 +V5/r))
h$type<- rownames(h)
rownames(h) <- NULL

HD24<- rbind(h, H)
HD24$Env<- "HELF24"




#2025
#Select traits and environments
e   <- levels(data_ag$Env)[4]

#broad sense heritability
data_sub <- data %>% 
      dplyr::filter(Env == e)
data_sub$GID<- as.factor(data_sub$GID)
    # Fit the model
mod_M1 <-  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ GID + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)
   
plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
H<- vpredict(mod_M1, H2~V1/(V1 +V5/r))
H$type<- rownames(H)
rownames(H) <- NULL

#narrow sense heritability
load("data/geno/WMB_master_geno.RData")
indp = data_sub$GID %in% rownames(A1)
data_sub = data_sub[indp,]
indg = rownames(A1) %in% data_sub$GID
A1 = A1[indg, indg]
Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
data_sub$GID <- as.factor(data_sub$GID)


mod_M1 <-  
  asreml(
  fixed    = as.formula(paste(traits, "~ 1")),
  random   = ~ vm(GID, Ginv.sparse) + ~ar1(Row):ar1(Column),
  residual = ~ units,
  data     = data_sub)


plot(mod_M1)
vc <- summary(mod_M1)$varcomp
rep_counts <- table(data_sub$GID)
r <- mean(rep_counts)
h<- vpredict(mod_M1, h2~V1/(V1 + V5/r))
h$type<- rownames(h)
rownames(h) <- NULL

HD25<- rbind(h, H)
HD25$Env<- "MCG25"





YLD<- rbind(HD21, HD22, HD23, HD24, HD25)
YLD$Trait<- "yield_kgha"
YLD
```




### **Heritability for MQ traits**
```{r}
data_mq$Env<- as.character(data_mq$Env)
data<- data_mq
data$Env<- as.factor(data$Env)
traits <- colnames(data_mq)[c(4:15)]
envs   <- levels(data$Env)#

#######################################################
#Broad sense heritability for MQ 23-24
######################################################
ratio_rows <- list()

for (tr in traits) {
  model_env <- list()
  
  for (e in envs) {
    data_sub <- data %>%
      filter(Env == e) %>%
      filter(.data[[tr]] > 0)
    data_sub<- data_sub %>% filter(!Fam == "NA") %>% filter(!GID == "NA")
    data_sub$Fam<- as.factor(data_sub$Fam)
    # Preprocessing as before...
    load("data/geno/WMB_master_geno.RData")
    indp = data_sub$GID %in% rownames(A1)
    data_sub = data_sub[indp,]
    indg = rownames(A1) %in% data_sub$GID
    A1 = A1[indg, indg]
    Ghat.bend <- G.tuneup(G = A1, bend = TRUE, eig.tol = 1e-03)$Gb
    Ginv.sparse <- G.inverse(G = Ghat.bend, sparse = TRUE)$Ginv
    ASRgenomics::match.kinship2pheno(K = A1, pheno.data = data_sub, indiv = "GID")
    data_sub$GID <- as.factor(data_sub$GID)
    
    # Center trait
    data_sub[[tr]] <- data_sub[[tr]] - mean(data_sub[[tr]], na.rm = TRUE)
    
    mod_M1 <- tryCatch({
      asreml(
        fixed    = as.formula(paste(tr, "~ 1")),
        random   = ~ vm(GID, Ginv.sparse) + ~Fam,
        residual = ~ units,
        data     = data_sub,
        ai.sing  = TRUE
      )
    }, error = function(err) {
      message(paste("Error fitting trait:", tr, "in environment:", e))
      return(NA)
    })
    
    model_env[[e]] <- mod_M1
    
    if (inherits(mod_M1, "asreml")) {
      vc <- summary(mod_M1)$varcomp
      r <- mean(table(data_sub$GID))
      H2 <- (vc[1, 1] + + vc[2, 1]) / (vc[1, 1] + vc[2, 1] + vc[3, 1] / r)
      h2 <- vc[2, 1]  / (vc[1, 1] + vc[2, 1] + vc[3, 1] / r)
      
      ratio_rows[[length(ratio_rows) + 1]] <- data.frame(
        Trait = tr,
        Environment = e,
        H2 = H2,
        h2 = h2
      )
    }
  }
  
  model_list[[tr]] <- model_env
}

# Combine all rows into a single data frame
H2mq <- bind_rows(ratio_rows)
H2mq$H2<- round(H2mq$H2, 2)
H2mq$h2<- round(H2mq$h2, 2)


str(H2mq)
H2ag<- as.data.frame(rbind(YLD, HD))


H2ag<- H2ag[,-2] %>% pivot_wider(values_from = Estimate, names_from = type)

colnames(H2ag)[1]<- "Environment"

H2s<- bind_rows(H2ag, H2mq)

```



### **MQ and ag heritability**
```{r, results='markup'}
trait_map <- c(
  "KernelWeight.mg." = "KW",
  "on6.64...."       = "on6/64", 
  "MaltExtract..."   = "ME",
  "BarleyProtein..." = "BP",
  "WortProtein..."   = "WP",
  "S.T"              = "S.T", 
  "DP..ASBC."       = "DP", 
  "Alpha.amylase.20.DU." = "AA", 
  "Beta.glucan.ppm." = "BG",
  "HD_JD" = "HD", 
  "yield_kgha" = "GY", 
  "FAN.ppm."         = "FAN", 
  "AdjunctQualityScore" = "Adj.Sc",
  "All_MaltQualityScore" = "All.Sc")


H2s <- H2s %>%
  mutate(Trait = recode(Trait, !!!trait_map))

pal <- c(
  KET21  = "cornsilk3",
  SNY22  = "palegreen2",
  MCG23  = "wheat2",
  HELF24 = "lightblue3", 
  MCG25 = "grey"
)

trait_order<- c( "GY" , "HD",  "KW", "on6/64" , "FAN" , "DP", "AA", "S.T" , "BG" , "ME",  "BP", "WP", "Adj.Sc", "All.Sc" )

H2s <- H2s %>%  mutate( Environment = trimws(as.character(Environment)),
    Environment = fct_relevel(Environment, env_order)  
  ) %>% mutate( Trait= trimws(as.character(Trait)),
    Trait = fct_relevel(Trait, trait_order)  
  )

H2s$h2 <- as.numeric(H2s$h2)
H2s$H2 <- as.numeric(H2s$H2)

H2s <- H2s %>%
  mutate(
    h2 = ifelse(Environment == "MCG23" & Trait == "AA", 0, h2),
    H2 = ifelse(Environment == "MCG23" & Trait == "AA", 0, H2)
  )


ggplot(H2s, aes(x=Environment,  y = h2, fill = Environment)) +
  geom_col()+
  scale_fill_manual(values= pal, drop= FALSE)+
  facet_grid(~Trait, scales= "free_x") +
  labs(x = "Environment", y = "h^2") +
  scale_y_continuous(breaks = c(0, 0.25,0.5, 0.75, 1)) +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 8, angle = 90), 
    legend.position = "bottom"
  )

ggplot(H2s, aes(x=Environment,  y = H2, fill = Environment)) +
  geom_col()+
  scale_fill_manual(values= pal, drop= FALSE)+
  facet_grid(~Trait, scales= "free_x") +
  labs(x = "Environment", y = "H^2") +
  scale_y_continuous(breaks = c(0, 0.25,0.5, 0.75, 1)) +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 8, angle = 90), 
    legend.position = "bottom"
  )
```

