---
title: "Untitled"
author: "sss322"
date: "2025-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
load("C:/Users/Siim Sepp/NY_WMB/data/wmb_multi_alldata.Rdata")
load("data/geno/WMB_master_geno.RData")
load("data/agronomic_mod_stats.Rdata")
```
```{r}
library(MASS)
library(dplyr)
library(tidyr)
library(asreml)
library(ASRtriala)
library(ASRgenomics)
```


```{r}
load("~/Documents/GitHub/NY_WMB/data/agronomic_models_select.Rdata")
load("~/Documents/GitHub/NY_WMB/data/agronomic_mod_stats.Rdata")
load("~/Documents/GitHub/NY_WMB/data/wmb_multi_alldata.Rdata")
load("~/Documents/GitHub/NY_WMB/data/geno/WMB_master_geno.RData")
load("~/Documents/GitHub/NY_WMB/analysis/agronomic_mod_stats.Rdata")
```


```{r}
model.setup <- ASRtriala::model.setup
specs.single <- model.setup %>%
  filter(add.rep == FALSE) %>% filter(add.ibk==FALSE)
```


```{r}

#asreml.license.activate()
#multi<- multi %>% filter(timepoint == "1")#  %>% filter(Env=="SNY22") 
multi<- data_ag
traits<- c("yield_kgha") 
env_levels <- levels(multi$Env) #unique(multi$Env)

all_models_stats <- list()
all_env_models_stats <- list()

for (env in env_levels) {
  env_data<- multi %>% filter(Env == env)
  ########################################Filtering the genotypes and creating a filterd GRM
  indp = env_data$GID %in% rownames(A1)
  table(indp)
  env_data = env_data[indp,]
  all(env_data$GID %in% rownames(A1))
  indg<-  rownames(A1) %in% env_data$GID
  A2<- A1[indg, indg]
  check<- match.kinship2pheno(K=A2, pheno.data = env_data, indiv = 'GID', clean = FALSE, mism = TRUE)
  Ghat.bend <- G.tuneup(G= A2, bend = TRUE, eig.tol= 1e-03 )$Gb
  Ginv.sparse<- G.inverse(G= Ghat.bend, sparse= TRUE)$Ginv
  env_data$GID <- as.factor(env_data$GID)
  #env_data$Block <- as.factor(env_data$Block)
  ########################################
  env_data<- fill.grid(env_data, row = "Row", col = "Column")
  all_indices_models_stats <- list()
  for (index in traits) {
    # Run the model on the entire env_data for the current index
    models.stats <- select.single(
      data = env_data,
      gen = "GID",
      #ibk = "Block",
      row = "Row",
      col = "Column",
      resp = index,
      type.gen = "random",
      data.model = specs.single,
      threshold = 3.5,
      pworkspace = "16gb",
      criteria = "logDopt"
    )
  
  all_indices_models_stats[[index]] <- models.stats$gof.stats
  }
  
  # Store the model stats for this Env in the overall list
  all_env_models_stats[[env]] <- all_indices_models_stats
}
# Save the overall stats for all Envs to a single file
save(all_env_models_stats, file = "agronomic_mod_stats.Rdata")

dim(all_env_models_stats$MCG25$yield_kgha
```



Calculating the Prediction accuracy while looping through models
```{r}
set.seed(1234)
data<- multi
data<- data %>% filter(timepoint == "1")
data$yield_m<- (data$yield_kgha - mean(data$yield_kgha , na.rm = TRUE))
data$yield_m<- data$yield_m *0.01
table(data$Env)
#outlier_values <- boxplot.stats(data$yield_m)$out
#out_ind <- which(data$yield_m %in% outlier_values)
#data<- data[-out_ind, ]


data_cv <- data %>% group_by(Env) %>% mutate(
    FoldID = sample(rep(1:5, length.out = n()))) %>% ungroup()

envs<- levels(data$Env)
e = envs[1]
traits<- "yield_m"
data$Block <- as.factor(data$Block)
folds <- unique(data_cv$FoldID)
res_kfold <- data.frame(Env = character(), Fold = integer(), Corr = numeric())
res_kfold <- data.frame()
trait_mods <- specs.single
head(specs.single)
str(specs.single)
for(t in traits)
  {for(e in envs)
    {for(m in 1:nrow(trait_mods))
         {for(f in folds){
      env_data <- data_cv[data_cv$Env == e, ]
      env_data[[t]][env_data$FoldID == f] <- NA
      env_data$GID<- as.factor(env_data$GID)
      env_data$Block<- as.factor(env_data$Block)
      #env_data<- fill.grid(env_data, row="Row", col ="Column")
      table(env_data$Row)
      env_mods<- all_env_models_stats[[e]]
      trait_mods<- env_mods[["yield_kgha"]]
      sel.m<- trait_mods[m,]
      fit_attempt <- tryCatch({
      # Fit the model
      Mod_kfold <- fit.single(
        env_data, 
        gen = "GID",
        row = "Row", 
        col = "Column",
        resp = t,
        ibk = "Block",
        type.gen = "random",
        add.row = sel.m$add.row, 
        add.col = sel.m$add.col,
        trend.row = sel.m$trend.row,
        trend.col = sel.m$trend.col,
        type.residual = sel.m$type.residual, 
        add.nugget = sel.m$add.nugget,
        threshold = 3.5, pworkspace = "16gb")
      #pred_vals <- predict(Mod_kfold, classify = "GID")$pvals
      pred_vals <- Mod_kfold$predictions
      held_out <- data_cv[data_cv$Env == e & data_cv$FoldID == f,c("GID", "Env", t)]
      merged <- merge(held_out, pred_vals[, c("GID", "predicted.value")], by = "GID")
      cor_val <- cor(merged[[t]], merged$predicted.value, use = "complete.obs")
      res_kfold <- rbind(res_kfold,data.frame(Trait = t, Env = e, Fold = f, Corr = cor_val, m=sel.m[1,1]))

    }, error = function(e) {
      # Handle the error: print a message, skip model
      print(e)
      print(sel.m)
      #cat("Error fitting model for Env =", e, "\n")
      #print(sel.m)
      # Return the unmodified 'all_predictions' so the loop continues
      return(res_kfold)
    })}}
    save(res_kfold, file= "CV.Rdata")}}


str(res_kfold)
table(res_kfold$Env
      )
```



```{r}
traits<- t
for(t in traits) {
  for(e in envs) {
    for(m in 1:nrow(trait_mods)) {
      for(f in folds) {
        env_data <- data_cv[data_cv$Env == e, ]
        env_data[[t]][env_data$FoldID == f] <- NA
        env_data$GID <- as.factor(env_data$GID)
        env_data$Block <- as.factor(env_data$Block)
        
        # Uncomment if needed for grid fill
        # env_data <- fill.grid(env_data, row = "Row", col = "Column")
        table(env_data$Row)
        
        env_mods <- all_env_models_stats[[e]]
        trait_mods_subset <- env_mods[["yield_kgha"]]  # Avoid overwriting trait_mods
        sel.m <- trait_mods_subset[m, ]
        
        # Try-catch for model fitting
        fit_attempt <- tryCatch({
          # Fit the model
          Mod_kfold <- fit.single(
            env_data, 
            gen = "GID",
            row = "Row", 
            col = "Column",
            resp = t,
            ibk = "Block",
            type.gen = "random",
            add.row = sel.m$add.row, 
            add.col = sel.m$add.col,
            trend.row = sel.m$trend.row,
            trend.col = sel.m$trend.col,
            type.residual = sel.m$type.residual, 
            add.nugget = sel.m$add.nugget,
            threshold = 3.5, pworkspace = "16gb"
          )
          
          # Get predictions
          pred_vals <- Mod_kfold$predictions
          held_out <- data_cv[data_cv$Env == e & data_cv$FoldID == f, c("GID", "Env", t)]
          merged <- merge(held_out, pred_vals[, c("GID", "predicted.value")], by = "GID")
          cor_val <- cor(merged[[t]], merged$predicted.value, use = "complete.obs")
          
          # Store results
          res_kfold <- rbind(res_kfold, data.frame(Trait = t, Env = e, Fold = f, Corr = cor_val, m = sel.m[1, 1]))
          
        }, error = function(e) {
          # Handle the error and continue
          cat("Error fitting model for Env =", e, "Trait =", t, ":\n", e$message, "\n")
          # Use next to continue to the next iteration of the fold loop
          next
        })
      }
    }
  }
}

# Save results after the loop finishes
save(res_kfold, file = "CV.Rdata")

```



```{r}
res_kfold_summary <- res_kfold %>%
  group_by(Trait, Env, m) %>%
  summarize(
    MeanCorr = mean(Corr, na.rm = TRUE),
    SDCorr   = sd(Corr, na.rm = TRUE)
  )
res_kfold_summary
table(res_kfold_summary$Env)
boxplot(res_kfold$Corr~ res_kfold$Env)
res_kfold$Env<- as.factor(res_kfold$Env)
```


