---
title: "Untitled"
author: "sss322"
date: "2025-12-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### **MQ and ag heritability plot**
```{r, results='markup'}

load("C:/Users/Siim Sepp/NY_WMB/heritabilites.Rdata")
str(H2ag)
str(H2mq)
H2ag<- H2ag[,-4]
H2mq<- H2mq[,-4]
H2s<- rbind(H2ag,H2mq)
                                                                                                                                                                          env_order<- c( "KET21", "SNY22" ,"MCG23","HELF24" , "MCG25" )                                          
trait_map <- c(
  "KernelWeight.mg." = "KW",
  "on6.64...."       = "on6/64", 
  "MaltExtract..."   = "ME",
  "BarleyProtein..." = "BP",
  "WortProtein..."   = "WP",
  "S.T"              = "S.T", 
  "DP..ASBC."       = "DP", 
  "Alpha.amylase.20.DU." = "AA", 
  "Beta.glucan.ppm." = "BG",
  "HD_JD" = "HD", 
  "yield_kgha" = "GY", 
  "FAN.ppm."         = "FAN", 
  "AdjunctQualityScore" = "Adj.Sc",
  "All_MaltQualityScore" = "All.Sc")


H2s <- H2s %>%
  mutate(Trait = recode(Trait, !!!trait_map))

pal <- c(
  KET21  = "cornsilk3",
  SNY22  = "palegreen2",
  MCG23  = "violet",
  HELF24 = "lightblue3", 
  MCG25 = "grey"
)

trait_order<- c( "GY" , "HD",  "KW", "on6/64" , "FAN" , "DP", "AA", "S.T" , "BG" , "ME",  "BP", "WP", "Adj.Sc", "All.Sc" )

H2s <- H2s %>%  mutate( Environment = trimws(as.character(Environment)),
    Environment = fct_relevel(Environment, env_order)  
  ) %>% mutate( Trait= trimws(as.character(Trait)),
    Trait = fct_relevel(Trait, trait_order)  
  )

H2s$H2 <- as.numeric(H2s$H2)

ggplot(H2s, aes(x=Environment,  y = H2, fill = Environment)) +
  geom_col()+
  scale_fill_manual(values= pal, drop= FALSE)+
  facet_grid(~Trait, scales= "free_x") +
  labs(x = "Environment", y = "H^2") +
  scale_y_continuous(breaks = c(0, 0.25,0.5, 0.75, 1)) +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 8, angle = 90)
  )


H2s<- H2s %>% filter(!Trait == "All.Sc")

ggplot(H2s, aes(x=Environment,  y = H2, fill = Environment)) +
  geom_col()+
  scale_fill_manual(values= pal, drop= FALSE)+
  facet_grid(~Trait, scales= "free_x") +
  labs(x = "Environment", y = "H^2") +
  scale_y_continuous(breaks = c(0, 0.25,0.5, 0.75, 1)) +
  theme(
    strip.text = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 16),
    axis.text  = element_text(size = 12, angle = 90,), 
    legend.position = "bottom"
  )
```



```{r}
load("C:/Users/Siim Sepp/NY_WMB/analysis/spec_BLUE_spatial.RData")
preds_sp<- preds
load("C:/Users/Siim Sepp/NY_WMB/data/mq_BLUP_spatial.RData")
preds_mq<- preds
```


```{r}
mq <- preds_mq[,-5] %>% pivot_wider(values_from = Predicted, names_from = VI)



sp <- preds_sp
sp<- sp %>% filter(Env %in% unique(mq$Env))

mq<- mq[,c(-5,-7)]

dat_cor <- sp %>%
  left_join(mq, by = c("GID", "Env"))

```


```{r}
mq_traits <- c(
  "KernelWeight.mg.",
  "on6.64....",
  #"BarleyColor.Agtron.",
  "MaltExtract...",
  #"WortClarity",
  "BarleyProtein...",
  "WortProtein...",
  "S.T",
  "DP..ASBC.",
  "Alpha.amylase.20.DU.",
  "FAN.ppm.",
  "AdjunctQualityScore"
)

trait_map <- c(
  "KernelWeight.mg." = "KW",
  "on6.64...."       = "on6/64", 
  "MaltExtract..."   = "ME",
  "BarleyProtein..." = "BP",
  "WortProtein..."   = "WP",
  "S.T"              = "S.T", 
  "DP..ASBC."       = "DP", 
  "Alpha.amylase.20.DU." = "AA", 
  "Beta.glucan.ppm." = "BG",
  "HD_JD" = "HD", 
  "yield_kgha" = "GY", 
  "FAN.ppm."         = "FAN", 
  "AdjunctQualityScore" = "Adj.Sc",
  "All_MaltQualityScore" = "All.Sc")







cor_results <- dat_cor %>%
  group_by(VI, Env, Timepoint) %>%
  summarise(
    across(
      all_of(mq_traits),
      ~ cor(Predicted, .x, use = "pairwise.complete.obs"),
      .names = "r_{.col}"
    ),
    n = sum(!is.na(Predicted)),
    .groups = "drop"
  )

cor_long <- cor_results %>%
  tidyr::pivot_longer(
    cols = starts_with("r_"),
    names_to = "MaltTrait",
    values_to = "r"
  ) %>%
  mutate(
    MaltTrait = gsub("^r_", "", MaltTrait)
  )


cor_long <- cor_long %>%
  mutate(
    MaltTrait_abbr = recode(MaltTrait, !!!trait_map)
  )

ggplot(cor_long, aes(VI, MaltTrait_abbr, fill = r)) +
  geom_tile() +
  facet_grid(Env ~ Timepoint) +
  scale_fill_gradient2(
    low = "blue", mid = "white", high = "red", midpoint = 0
  ) +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text.x = element_text(size = 8, angle = 90)
  ) +
  labs(
    title = "Genotypic correlations between VI and malt quality traits",
    fill = "r",
    x = "Vegetation Index",
    y = "Malt quality trait"
  )


cor_long1<- cor_long %>% filter(VI== "PSRI")

library(ggplot2)
cor_long1$Timepoint<- cor_long1$Timepoint-1

ggplot(cor_long1, aes(Timepoint, MaltTrait_abbr, fill = r)) +
  geom_tile(color = "grey85", linewidth = 0.3) +
  facet_wrap(~ Env, nrow = 1, scales= "free") +
  scale_fill_gradient2(
    low = "blue", 
    mid = "white", 
    high = "red",
    midpoint = 0,
    limits = c(-0.5, 0.5),
    name = expression(r[g])
  ) +
  theme(
    strip.text = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 16, face = "bold"),
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    panel.grid = element_blank(),
    legend.position = "right"
  ) +
  labs(
   # title = "Genotypic correlations between vegetation indices and malt quality traits",
    x = "Timepoint",
    y = "Malt quality trait"
  )
```




Prediction plots. 
```{r}
load("GP_MM_results_mq_predsD.Rdata")   #GP pred
load("GP_MM_results_mq_rawD.Rdata")     #GP raw
load("MT_mq_res_raw_spD.Rdata")         #MT raw
load("MT_mq_res_prD.Rdata")             #MT_pred
load("GP_DK_results_mq_raw_selD.Rdata") #DK raw
load("GP_DK_results_mq_prD.Rdata")      #DK sel


GP_DK_results_mq_pr$results
GP_DK_results_mq_raw_sel$results
GP_MM_results_mq_preds$results
GP_MM_results_mq_raw$results
MT_mq_res_pr$results
MT_mq_res_raw_sp$results
```



**Merge MT GP**
```{r}
MT_mq_res_pr$results$BLUE <- "Two"
MT_mq_res_raw_sp$results$BLUE <- "One"

MT_res_raw<- rbind(MT_mq_res_raw_sp$results, MT_mq_res_pr$results)
colnames(MT_res_raw)
MT_res_raw<- MT_res_raw[-4:-5]
#MT_res_raw$BLUE<- "One"
MT_res_raw$type<- NA
MT_res_raw$met<- "MT"
```


**merge DK GP**
```{r}
GP_DK_results_mq_pr$results$type<- "sel"
GP_DK_results_mq_raw_sel$results$type<- "sel"

GP_DK_results_mq_pr$results$BLUE<- "Two"
GP_DK_results_mq_raw_sel$results$BLUE <- "One"

GP_DK_res<- rbind(GP_DK_results_mq_raw_sel$results, GP_DK_results_mq_pr$results)

GP_DK_res<- GP_DK_res %>% filter(!Trait == "BarleyColor.Agtron.") %>% filter(!Trait == "WortClarity")

str(GP_DK_res)
GP_DK_res <- GP_DK_res[c(2,3,6,10, 11)]
GP_DK_res$met<- "DK"
#GP_DK_res$BLUE<- "One"
GP_DK_res$Cor_Trait<- NA
```


```{r}
GP_MM_results_mq_preds$results$BLUE <- "Two"
GP_MM_results_mq_raw$results$BLUE <- "One"
GP_res<- rbind(GP_MM_results_mq_preds$results, GP_MM_results_mq_raw$results)

colnames(GP_res)
GP_res<- GP_res[,c(2,3,6,7)]
GP_res$type<- "GP"
GP_res$Cor_Trait<- "NA"
GP_res$met <- "GP"


colnames(GP_res)
colnames(GP_DK_res)
colnames(MT_res_raw)
```

#Merge GP, MT, DK. 
```{r}
#GP_DK_res<- GP_DK_res %>% filter(type== "comb")
GP_res<- rbind(GP_DK_res, GP_res, MT_res_raw)

GP_res <- GP_res %>%
  mutate(Trait = recode(Trait, !!!trait_map))

GP_res <- GP_res %>% filter(!Trait == "BarleyColor.Agtron.") %>% filter(!Trait == "WortClarity")
env_order<- c( "KET21", "SNY22" )

unique(GP_res$Trait)
GP_res <- GP_res  %>%  
  mutate( Environment = trimws(as.character(Env)),
          Environment = fct_relevel(Env, env_order)) %>%
  mutate( Trait= trimws(as.character(Trait)),
          Trait = fct_relevel(Trait, trait_order))


cv_summary <- GP_res %>%
  group_by(Trait, met) %>%
  summarise(
    mean_accuracy = round(mean(Cor, na.rm = TRUE),2),
    sd_accuracy   = round(sd(Cor, na.rm = TRUE),2),
    n  = n()
    )

cv_summary

```



```{r}
str(GP_res)
cort<- c("NDVI" ,"PC1", "PC2",  "FPC2", "PC3",  "FPC3")

table(GP_res$Trait, GP_res$met)
table(GP_res$met, GP_res$type)
# %>% filter(type == "comb") %>% filter()
#ag traits

GP_res1<- GP_res 

ggplot(GP_res1, aes(x = Trait, y = Cor, fill = met)) +
  geom_boxplot() +
   facet_grid(~Environment, scales = "free") +
  labs(
    title = " ",
    y = "Prediction Accuracy",
    x = "Model Method"
  ) +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 10, angle = 90),
    legend.position = "bottom"
  )

table(GP_res$met, GP_res$Trait)

ggplot(GP_res1, aes(x = met, y = Cor, fill = met)) +
  geom_boxplot() +
   facet_grid(~Trait, scales = "free") +
  labs(
    title = " ",
    y = "CV Prediction Accuracy",
    x = "Model Method"
  ) +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 10, angle = 90),
    legend.position = "bottom"
  )


#mq traits

GP_res1<- GP_res %>% filter(BLUE == "One") %>% filter(!Trait %in% agtrait) %>% filter(!Cor_Trait %in% cort)


ggplot(GP_res1, aes(x = Trait, y = Cor, fill = met)) +
  geom_boxplot() +
   facet_grid(~Environment, scales = "free") +
  labs(
    title = " ",
    y = "Prediction Accuracy",
    x = "Model Method"
  ) +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 10, angle = 90),
    legend.position = "bottom"
  )

GP_res1<- GP_res1 %>% filter(met == "GP") 

ggplot(GP_res1, aes(x = Trait, y = Cor, fill = Trait)) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0, 1)) +
   facet_grid(~Trait, scales = "free") +
  labs(
    title = " ",
    y = "CV Prediction Accuracy",
    x = "Model Method"
  ) +
  theme(
    strip.text = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 16),
    axis.text  = element_text(size = 16, angle = 90),
    legend.position = "bottom"
  )
```



